name: HumanVision
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - altgraph=0.17.3
  - appdirs=1.4.4
  - blas=1.0=mkl
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2023.05.30
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - cycler=0.11.0
  - eigen=3.4.0
  - fonttools=4.25.0
  - freetype=2.10.4
  - glib=2.69.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - hdf5=1.10.6
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - libbrotlicommon=1.0.9
  - libclang=12.0.0
  - libffi=3.4.2
  - libpng=1.6.37
  - libtiff=4.0.9
  - matplotlib=3.5.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_random=1.2.2
  - numexpr=2.8.4
  - numpy=1.23.5
  - opencv=4.6.0
  - openssl=1.1.1v
  - pandas=1.5.3
  - pillow=9.3.0
  - pip=22.3.1
  - pyopenssl=23.0.0
  - pyqt5-sip=12.11.0
  - python-dateutil=2.8.2
  - pytz=2022.7
  - requests=2.28.1
  - scipy=1.10.1
  - sip=6.6.2
  - sqlite=3.40.1
  - tk=8.6.12
  - tornado=6.2
  - urllib3=1.26.15
  - zlib=1.2.13

  
  - pip:
    - brewer2mpl==1.4.1
    - click==8.1.3
    - colorama==0.4.6
    - et-xmlfile==1.1.0
    - openpyxl==3.1.2
    - pefile==2023.2.7
    - pyinstaller==5.12.0
    - pyinstaller-hooks-contrib==2023.3
    - pyqt5==5.15.9
    - pyqt5-tools==5.15.9.3.3
    - python-dotenv==1.0.0
    - pywin32-ctypes==0.2.1
    - seaborn==0.12.2